import { normalizeGuid } from "../sketch/binary.js";
import type { BrushSizeRange } from "./brush-size.js";

export type BrushSupportStatus = "supported" | "fallback" | "unsupported";
export type BrushPressureSizeRange = readonly [number, number];
export type BrushPressureOpacityRange = readonly [number, number];

export type BrushGeometryFamily =
  | "ribbon"
  | "tube"
  | "emissive"
  | "particle"
  | "unsupported";

export type BrushMaterialFamily =
  | "standard"
  | "unlit"
  | "additive"
  | "particle"
  | "fallback";

export interface OpenBrushExportManifest {
  tiltBrushVersion?: string;
  tiltBrushBuildStamp?: string;
  brushes: Record<string, OpenBrushExportBrush>;
}

export interface OpenBrushExportBrush {
  guid: string;
  name: string;
  folderName: string;
  shaderVersion: string;
  vertexShader?: string;
  fragmentShader?: string;
  blendMode: number;
  enableCull: boolean;
  textures?: Record<string, string>;
  textureSizes?: Record<string, [number, number]>;
  floatParams?: Record<string, number>;
  vectorParams?: Record<string, [number, number, number, number]>;
  colorParams?: Record<string, [number, number, number, number]>;
}

export interface BrushShaderAssetInfo {
  /** "handcrafted" = authored GLSL from the Open Brush repo; "template" = generated by the official template pipeline. */
  glslSource: "handcrafted" | "template";
  /** True when the vertex stage is the shared VertDefault program, i.e. it only consumes position/normal/color/uv. */
  vertexIsDefault: boolean;
  vertexShaderFile: string;
  fragmentShaderFile: string;
  /** Manifest texture param name (e.g. "MainTex") → extracted file under public/openbrush/textures/. */
  textureFiles: Record<string, string>;
  textureImporters: Record<string, BrushTextureImporterSettings>;
}

export interface BrushTextureImporterSettings {
  sRGB: boolean;
  mipmaps: boolean;
  filter: "point" | "bilinear" | "trilinear";
  wrapU: "repeat" | "clamp" | "mirror" | "mirror-once";
  wrapV: "repeat" | "clamp" | "mirror" | "mirror-once";
  anisotropy: number;
  mipBias: number;
}

export interface BrushGeometryParams {
  brushSizeRange?: BrushSizeRange;
  tileRate?: number;
  textureAtlasV?: number;
  renderBackfaces?: boolean;
  backfaceHueShift?: number;
  tubeStoreRadiusInTexcoord0Z?: boolean;
  tubeCapAspect?: number;
  tubeSideCount?: number;
  tubeEndCaps?: boolean;
  tubeHardEdges?: boolean;
  tubeUvStyle?: "distance" | "stretch";
  tubeShapeModifier?: number;
  tubeTaperScalar?: number;
  tubePetalDisplacementAmount?: number;
  tubePetalDisplacementExponent?: number;
  tubeBreakAngleMultiplier?: number;
  ribbonUvStyle?: "distance" | "stretch";
  ribbonOffsetInTexcoord1?: boolean;
  opacity?: number;
  solidMinLengthMeters?: number;
  audioReactive?: boolean;
  colorLuminanceMin?: number;
  colorSaturationMax?: number;
  particleRate?: number;
  sprayRateMultiplier?: number;
  particleSpeed?: number;
  particleInitialRotationRange?: number;
  particleRandomizeAlpha?: boolean;
  particleSizeVariance?: number;
  particlePositionVariance?: number;
  particleRotationVariance?: number;
  particleSizeRatio?: [number, number];
}

/** Geometry generator family resolved from the Unity brush prefab. */
export type BrushGeneratorFamily =
  | "ribbon"
  | "tube"
  | "particle"
  | "quad-stamp"
  | "thick-strip"
  | "geometry"
  | "hull";

/** Raw shape of one entry in src/brushes/generated/brush-assets.json. */
export interface BrushAssetRecord {
  catalogSection?: "standard" | "experimental";
  catalogOrder?: number;
  glslSource: "handcrafted" | "template";
  vertexIsDefault: boolean;
  vertexShader: string;
  fragmentShader: string;
  textures: Record<
    string,
    {
      file: string;
      resolved: boolean;
      importer?: BrushTextureImporterSettings;
    }
  >;
  geometry?: BrushGeometryParams & {
    brushSizeRange?: [number, number];
    pressureSizeRange?: [number, number];
    pressureOpacityRange?: [number, number];
  };
  generatorClass?: string;
  generatorFamily?: BrushGeneratorFamily;
  supersededByGuid?: string;
  /** Open Brush GUI tags from the descriptor (e.g. "default", "experimental", "audioreactive"). */
  tags?: string[];
  /** Extracted picker button icon file under public/openbrush/icons/. */
  buttonIcon?: string;
}

export interface BrushInventoryEntry extends OpenBrushExportBrush {
  catalogSection?: "standard" | "experimental";
  catalogOrder?: number;
  supportStatus: BrushSupportStatus;
  geometryFamily: BrushGeometryFamily;
  materialFamily: BrushMaterialFamily;
  brushSizeRange: BrushSizeRange;
  pressureSizeRange: BrushPressureSizeRange;
  pressureOpacityRange: BrushPressureOpacityRange;
  unsupportedReason?: string;
  shaderAssets?: BrushShaderAssetInfo;
  geometryParams?: BrushGeometryParams;
  generatorClass?: string;
  /** Newer brush GUID that replaces this one (hidden from the picker, still renders). */
  supersededByGuid?: string;
  /** Open Brush GUI tags from the descriptor. */
  tags: string[];
  /** Picker button icon file under public/openbrush/icons/, when extracted. */
  buttonIconFile?: string;
  /** True when the brush should be offered in the brush picker. */
  pickerVisible: boolean;
  /** True when Open Brush includes this manifest brush under its default tag rules. */
  portRequired: boolean;
}

export interface BrushInventorySummary {
  total: number;
  supported: number;
  fallback: number;
  unsupported: number;
}

interface BrushSupportDecision {
  supportStatus: BrushSupportStatus;
  geometryFamily: BrushGeometryFamily;
  materialFamily: BrushMaterialFamily;
  pickerVisible: boolean;
  unsupportedReason?: string;
}

const DEFAULT_BRUSH_SIZE_RANGE: BrushSizeRange = [0.05, 3];
const DEFAULT_PRESSURE_SIZE_RANGE: BrushPressureSizeRange = [0.1, 1];
const DEFAULT_PRESSURE_OPACITY_RANGE: BrushPressureOpacityRange = [1, 1];

/**
 * Support is derived from extracted reference data: the geometry generator
 * class behind the brush prefab and whether the exported shader's vertex
 * stage is the shared default (i.e. our generated geometry satisfies it).
 * The picker offers only extrusion brushes (ribbon/tube) that render with
 * their real shaders; particle/spray brushes wait for a proper particle
 * system, and superseded brush versions stay hidden like in Open Brush.
 */
function resolveBrushSupport(
  brush: OpenBrushExportBrush,
  record: BrushAssetRecord | undefined,
): BrushSupportDecision {
  const generatorFamily = record?.generatorFamily;
  if (!record || !generatorFamily) {
    return {
      supportStatus: "unsupported",
      geometryFamily: "unsupported",
      materialFamily: "fallback",
      pickerVisible: false,
      unsupportedReason:
        "Brush geometry generator is not mapped to an IWSDK geometry family yet.",
    };
  }

  const materialFamily: BrushMaterialFamily =
    generatorFamily === "particle"
      ? "particle"
      : brush.blendMode === 2
        ? "additive"
        : "Color" in (brush.colorParams ?? {})
          ? "standard"
          : "unlit";

  if (generatorFamily === "ribbon" || generatorFamily === "tube") {
    const geometryFamily: BrushGeometryFamily =
      generatorFamily === "tube"
        ? "tube"
        : brush.blendMode === 2
          ? "emissive"
          : "ribbon";
    const hasWaveformContract =
      brush.name === "Waveform" &&
      record.generatorClass === "QuadStripBrushStretchUV";
    const hasDoubleTaperedContract =
      (brush.name === "DoubleTaperedMarker" ||
        brush.name === "DoubleTaperedFlat") &&
      record.generatorClass === "FlatGeometryBrush" &&
      record.geometry?.ribbonOffsetInTexcoord1 === true;
    if (
      !record.vertexIsDefault &&
      !hasWaveformContract &&
      !hasDoubleTaperedContract
    ) {
      return {
        supportStatus: "fallback",
        geometryFamily,
        materialFamily,
        pickerVisible: false,
        unsupportedReason:
          "Brush needs vertex-shader features the geometry generator does not emit yet.",
      };
    }
    // Match Open Brush's own curation: its default brush panel shows only
    // "default"-tagged brushes; "experimental"-tagged ones (many of which are
    // near-duplicates or variants) hide behind an opt-in setting. They stay
    // fully supported so sketches that use them keep their real shaders.
    return {
      supportStatus: "supported",
      geometryFamily,
      materialFamily,
      pickerVisible:
        record.supersededByGuid === undefined &&
        (record.tags ?? []).includes("default"),
    };
  }

  if (generatorFamily === "particle") {
    const hasGeniusParticleContract =
      record.generatorClass === "GeniusParticlesBrush";
    const hasSprayParticleContract =
      record.generatorClass === "SprayBrush" && record.vertexIsDefault;
    const hasMidpointParticleContract =
      record.generatorClass === "MidpointPlusLifetimeSprayBrush" &&
      record.vertexIsDefault;
    const hasParticleContract =
      hasGeniusParticleContract ||
      hasSprayParticleContract ||
      hasMidpointParticleContract;
    return {
      supportStatus: hasParticleContract ? "supported" : "fallback",
      geometryFamily: "particle",
      materialFamily,
      pickerVisible:
        hasParticleContract &&
        record.supersededByGuid === undefined &&
        (record.tags ?? []).includes("default"),
      unsupportedReason: hasParticleContract
        ? undefined
        : "Spray particle brushes are deferred until their packed vertex contract exists.",
    };
  }

  return {
    supportStatus: "unsupported",
    geometryFamily: "unsupported",
    materialFamily: "fallback",
    pickerVisible: false,
    unsupportedReason: `Brush geometry family "${generatorFamily}" is not supported yet.`,
  };
}

function toRange(
  value: [number, number] | undefined,
  fallback: readonly [number, number],
  minimum = 0,
): readonly [number, number] {
  if (
    !value ||
    !Number.isFinite(value[0]) ||
    !Number.isFinite(value[1]) ||
    value[0] < minimum ||
    value[1] < minimum
  ) {
    return fallback;
  }
  return value;
}

function toShaderAssetInfo(
  record: BrushAssetRecord | undefined,
): BrushShaderAssetInfo | undefined {
  if (!record) {
    return undefined;
  }
  const textureFiles: Record<string, string> = {};
  const textureImporters: Record<string, BrushTextureImporterSettings> = {};
  for (const [param, texture] of Object.entries(record.textures ?? {})) {
    if (texture.resolved) {
      textureFiles[param] = texture.file;
      if (texture.importer) {
        textureImporters[param] = texture.importer;
      }
    }
  }
  return {
    glslSource: record.glslSource,
    vertexIsDefault: record.vertexIsDefault,
    vertexShaderFile: record.vertexShader,
    fragmentShaderFile: record.fragmentShader,
    textureFiles,
    textureImporters,
  };
}

export function buildBrushInventoryFromExportManifest(
  manifest: OpenBrushExportManifest,
  assetRecords?: Record<string, BrushAssetRecord>,
): BrushInventoryEntry[] {
  const entries = Object.entries(manifest.brushes).map(([key, brush]) => {
    const guid = normalizeGuid(brush.guid);
    if (normalizeGuid(key) !== guid) {
      throw new Error(`Brush manifest key ${key} does not match brush guid ${brush.guid}`);
    }

    const assetRecord = assetRecords?.[guid];
    const support = resolveBrushSupport(brush, assetRecord);
    const tags = assetRecord?.tags ?? [];
    const portRequired =
      assetRecord?.catalogSection !== undefined &&
      !tags.includes("broken") &&
      (tags.includes("default") || tags.includes("experimental"));
    return {
      ...brush,
      guid,
      supportStatus: support.supportStatus,
      geometryFamily: support.geometryFamily,
      materialFamily: support.materialFamily,
      brushSizeRange: toRange(
        assetRecord?.geometry?.brushSizeRange,
        DEFAULT_BRUSH_SIZE_RANGE,
        Number.MIN_VALUE,
      ),
      pressureSizeRange: toRange(
        assetRecord?.geometry?.pressureSizeRange,
        DEFAULT_PRESSURE_SIZE_RANGE,
      ),
      pressureOpacityRange: toRange(
        assetRecord?.geometry?.pressureOpacityRange,
        DEFAULT_PRESSURE_OPACITY_RANGE,
      ),
      unsupportedReason: support.unsupportedReason,
      shaderAssets: toShaderAssetInfo(assetRecord),
      geometryParams: assetRecord?.geometry,
      generatorClass: assetRecord?.generatorClass,
      supersededByGuid: assetRecord?.supersededByGuid,
      tags,
      buttonIconFile: assetRecord?.buttonIcon,
      catalogSection: assetRecord?.catalogSection,
      catalogOrder: assetRecord?.catalogOrder,
      // The standard Open Brush manifest defines picker membership and order.
      // Fidelity status is deliberately independent: incomplete brushes use
      // the existing fallback geometry/material instead of disappearing.
      pickerVisible: portRequired && assetRecord?.catalogSection === "standard",
      portRequired,
    };
  });

  entries.sort(compareOpenBrushCatalogOrder);
  return entries;
}

function compareOpenBrushCatalogOrder(
  left: BrushInventoryEntry,
  right: BrushInventoryEntry,
): number {
  const sectionRank = (section: BrushInventoryEntry["catalogSection"]): number =>
    section === "standard" ? 0 : section === "experimental" ? 1 : 2;
  return (
    sectionRank(left.catalogSection) - sectionRank(right.catalogSection) ||
    (left.catalogOrder ?? Number.MAX_SAFE_INTEGER) -
      (right.catalogOrder ?? Number.MAX_SAFE_INTEGER) ||
    left.name.localeCompare(right.name) ||
    left.guid.localeCompare(right.guid)
  );
}

export function summarizeBrushInventory(
  entries: readonly BrushInventoryEntry[],
): BrushInventorySummary {
  const summary: BrushInventorySummary = {
    total: entries.length,
    supported: 0,
    fallback: 0,
    unsupported: 0,
  };

  for (const entry of entries) {
    summary[entry.supportStatus] += 1;
  }

  return summary;
}

export function findBrushByGuid(
  entries: readonly BrushInventoryEntry[],
  guid: string,
): BrushInventoryEntry | undefined {
  const normalized = normalizeGuid(guid);
  return entries.find((entry) => entry.guid === normalized);
}
